### ISSUE TITLE
报错求解「Call to undefined method Illuminate\Foundation\Application::share() 」

### ISSUE THREAD

**Issue by wingofsky** [zhaohehe/z-repository#3]
LARAVEL5.4运行php artisan vendor:publish后报错：

[Symfony\Component\Debug\Exception\FatalThrowableError]              
Call to undefined method Illuminate\Foundation\Application::share() 

是版本的问题吗。。。。求解

**Comment by zhaohehe** [comment]
版本问题  当年还没有5.4  😆  Illuminate\Foundation\Application::share() 应该被laravel移除了

**Comment by wingofsky** [comment]
尴尬~~~求教应该怎么修改。。。。

**Comment by zhaohehe** [comment]
最新版本已修复   可支持laravel5.5
