### ISSUE TITLE
有没有laravel5.4能使用的版本呢？

### ISSUE THREAD

**Issue by hooklife** [zhaohehe/z-repository#4]
使用最新版本
`php artisan make:repository`
命令不好用

**Comment by meitesi** [comment]
也发现这个问题

**Comment by zhaohehe** [comment]
已修复
对应版本  https://github.com/zhaohehe/z-repository/tree/v1.1.0

使用方法 composer require "zhaohehe/zrepository:1.1.0"

**Comment by hooklife** [comment]
感谢
